export * from './AboutUs/AboutUs';
export * from './Choice/Choice';
export * from './Contacts/Contacts';
export * from './Gallery/Gallery';
export * from './Hero/Hero';
export * from './News/News';
export * from './OurTeam/OurTeam';
export * from './Practice/Practice';
export * from './Price/Price';
